[package]
name = "test-contract"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { path = "../../near-sdk" }
wasmcov = "0.2"

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = false
debug = false
panic = "abort"

[dev-dependencies] 
near-sdk = { path = "../../near-sdk", features = ["unit-testing"] } 
